
ERROR:root:name 'url' is not defined
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 48, in request_freess_cx
    info = {'message': msg, 'url': url, 'name': str(title)}
NameError: name 'url' is not defined
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 64, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 59, in request_freess_cx
    logging.exception(e, stack_info=True)
ERROR:root:name 'url' is not defined
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 50, in request_freess_cx
    info = {'message': msg, 'url': url, 'name': str(title)}
NameError: name 'url' is not defined
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 66, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 61, in request_freess_cx
    logging.exception(e, stack_info=True)
ERROR:root:name 'url' is not defined
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 50, in request_freess_cx
    info = {'message': msg, 'url': url, 'name': str(title)}
NameError: name 'url' is not defined
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 66, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 61, in request_freess_cx
    logging.exception(e, stack_info=True)
ERROR:root:name 'url' is not defined
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 51, in request_freess_cx
    info = {'message': msg, 'url': url, 'name': str(title)}
NameError: name 'url' is not defined
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 67, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 62, in request_freess_cx
    logging.exception(e, stack_info=True)
ERROR:root:'NoneType' object is not callable
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 49, in request_freess_cx
    soup = BeautifulSoup(title,'lxml')
  File "C:\Users\NiuHe\Anaconda3\lib\site-packages\bs4\__init__.py", line 191, in __init__
    markup = markup.read()
TypeError: 'NoneType' object is not callable
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 69, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 64, in request_freess_cx
    logging.exception(e, stack_info=True)
ERROR:root:'NoneType' object is not callable
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 50, in request_freess_cx
    soup = BeautifulSoup(title,'lxml')
  File "C:\Users\NiuHe\Anaconda3\lib\site-packages\bs4\__init__.py", line 191, in __init__
    markup = markup.read()
TypeError: 'NoneType' object is not callable
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 70, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 65, in request_freess_cx
    logging.exception(e, stack_info=True)
ERROR:root:'NoneType' object is not callable
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 51, in request_freess_cx
    soup = BeautifulSoup(title,'lxml')
  File "C:\Users\NiuHe\Anaconda3\lib\site-packages\bs4\__init__.py", line 191, in __init__
    markup = markup.read()
TypeError: 'NoneType' object is not callable
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 71, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 66, in request_freess_cx
    logging.exception(e, stack_info=True)
ERROR:root:'NoneType' object is not callable
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 53, in request_freess_cx
    soup = BeautifulSoup(title,'lxml')
  File "C:\Users\NiuHe\Anaconda3\lib\site-packages\bs4\__init__.py", line 191, in __init__
    markup = markup.read()
TypeError: 'NoneType' object is not callable
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 73, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 68, in request_freess_cx
    logging.exception(e, stack_info=True)
ERROR:root:name 'url' is not defined
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 57, in request_freess_cx
    info = {'message': msg, 'url': url, 'name': str(title)}
NameError: name 'url' is not defined
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 73, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 68, in request_freess_cx
    logging.exception(e, stack_info=True)
ERROR:root:name 'url' is not defined
Traceback (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 53, in request_freess_cx
    info = {'message': msg, 'url': url, 'name': str(title)}
NameError: name 'url' is not defined
Stack (most recent call last):
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 69, in <module>
    server, info = request_freess_cx()
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 35, in wrapper
    return func(response)
  File "E:/Temp/ShadowSocksShare-OpenShift/app/ss/test.py", line 64, in request_freess_cx
    logging.exception(e, stack_info=True)
